"""Find item templates whose realm does not match their model's realm, and write the bot skip list.

  python tools\\claude-version\\cross_realm_gear_audit.py            (report only)
  python tools\\claude-version\\cross_realm_gear_audit.py --write    (also rewrite BotCrossRealmGear.cs)

A Midgard item that uses a Hibernia model (for example the "...woven pointed steeple
hat3" wizard hats on model 1279) only has meshes for Hibernian races, so a Valkyn or
Troll wearing it gets a mesh that does not fit. Weapons and shields fit everyone but
look like another realm's gear. Bots (gamebots and companions) skip every listed
template when they pick equipment; the items stay in the database for players.

The model's realm comes from its name in the client's objects.csv ("Alb", "Mid",
"Hib", "Albion", "Midgard", "Hibernia"). Models with no realm in their name are
never listed. Read-only against the database.
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "pet-art"))
from daoc_catalog import csv_rows, gamedata  # noqa: E402

ROOT = HERE.parents[1]
DB = ROOT / "runtime" / "data" / "opendaoc.sqlite3.db"
OUT = ROOT / "source" / "server" / "GameServer" / "bots" / "BotCrossRealmGear.cs"
REALMS = {1: "Albion", 2: "Midgard", 3: "Hibernia"}


def model_realms(name: str) -> set[int]:
    text = (name or "").lower()
    found = set()
    if re.search(r"\balb(ion)?\b", text):
        found.add(1)
    if re.search(r"\bmid(gard)?\b", text):
        found.add(2)
    if re.search(r"\bhib(ernia)?\b", text):
        found.add(3)
    return found


def audit() -> list[tuple[str, int, int, str]]:
    names = {int(r[0]): r[1].strip() for r in csv_rows(gamedata(), "objects.csv")
             if r and r[0].strip().isdigit()}
    db = sqlite3.connect(f"file:{DB.as_posix()}?mode=ro", uri=True, timeout=10)
    rows = []
    for id_nb, model, realm in db.execute(
            "select Id_nb, Model, Realm from itemtemplate where IsPickable=1 and Realm in (1,2,3)"):
        realms = model_realms(names.get(model, ""))
        if realms and realm not in realms:
            rows.append((id_nb, realm, model, names[model]))
    return sorted(rows, key=lambda row: (row[1], row[0].lower()))


def write_cs(rows: list[tuple[str, int, int, str]]) -> None:
    lines = [
        "using System;",
        "using System.Collections.Generic;",
        "using DOL.Database;",
        "",
        "namespace DOL.GS",
        "{",
        "    /// <summary>",
        "    /// Item templates whose realm does not match their model's realm (generated by",
        "    /// tools/claude-version/cross_realm_gear_audit.py from the client's objects.csv). A Midgard hat on",
        "    /// a Hibernia model has no Valkyn or Troll mesh, so it does not fit; weapons and",
        "    /// shields just look like another realm's. Bots never pick these when equipping;",
        "    /// the items stay in the database for players.",
        "    /// </summary>",
        "    public static class BotCrossRealmGear",
        "    {",
        "        private static readonly HashSet<string> ExcludedTemplateIds = new(StringComparer.OrdinalIgnoreCase)",
        "        {",
    ]
    for id_nb, realm, model, name in rows:
        comment = f"{REALMS[realm]} item on model {model} '{name}'".replace("*/", "")
        lines.append(f'            "{id_nb}", // {comment}')
    lines += [
        "        };",
        "",
        "        public static int Count => ExcludedTemplateIds.Count;",
        "",
        "        public static bool IsExcluded(DbItemTemplate template) =>",
        "            template != null && !string.IsNullOrEmpty(template.Id_nb) && ExcludedTemplateIds.Contains(template.Id_nb);",
        "    }",
        "}",
        "",
    ]
    OUT.write_text("\r\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = audit()
    by_realm = {}
    for _, realm, _, _ in rows:
        by_realm[REALMS[realm]] = by_realm.get(REALMS[realm], 0) + 1
    print(f"{len(rows)} templates use another realm's model: {by_realm}")
    if "--write" in sys.argv:
        write_cs(rows)
        print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
