"""Writes the bot camp list section for the classic quest monster spawns (apply_world.py's world_preview.json) into
GameServer/bots/autonomous/data/classic165_period_restored_spawn_ids.txt, so the gamebots grind them like any camp
(owner 2026-10-07: kill-task camps and new quest spawns must be bot grind goals). Species monsters only: the named
quest monsters stay in ClassicQuests' QuestMonsterIds, which the gamebots leave alone. Re-run after apply_world.py;
rebuild the server to ship it."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
P = os.path.join(HERE, '..', '..', '..', 'server', 'GameServer', 'bots', 'autonomous', 'data', 'classic165_period_restored_spawn_ids.txt')
MARK = '# classic quest monster camps (generated by research/period-data/quests/camp_ids.py)'
raw = open(P, encoding='utf-8', newline='').read()
nl = '\r\n' if '\r\n' in raw else '\n'
head, _, rest = raw.partition(nl + MARK + nl)
tail = ''
if rest:  # keep any section written after this one
    lines = rest.split(nl)
    cut = next((k for k, l in enumerate(lines) if l.startswith('#')), len(lines))
    tail = nl.join(lines[cut:])
mobs = json.load(open(os.path.join(HERE, 'world_preview.json'), encoding='utf-8'))['mobs']
ids = list(dict.fromkeys(m['Mob_ID'] for m in mobs if not m['Realm'] and m['Name'][:1].islower()))
out = head.rstrip(nl) + nl + MARK + nl + nl.join(ids) + nl + (tail.rstrip(nl) + nl if tail.strip() else '')
open(P, 'w', encoding='utf-8', newline='').write(out)
print('camp ids', len(ids))
