"""Writes "GOAL 8 QUEST LEDGER.md" next to the goals ledger: everything in the classic quest build that is not straight
from a period page - placeholders, substitutions, borrowed looks and stats, hand-resolved places - so the owner can
review it. Generated from the pipeline's own outputs; re-run after every rebuild.   python ledger_goal8.py"""
import collections, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'GOAL 8 QUEST LEDGER.md')


def load(name, default=None):
    p = os.path.join(HERE, name)
    return json.load(open(p, encoding='utf-8')) if os.path.exists(p) else default


prev = load('dataquest_preview.json', {'rows': [], 'item_rows': []})
conf = load('classic-quests.preview.json', {'Quests': {}})
world = load('world_preview.json', {'mobs': [], 'skipped': []})
plan = load('spawn_plan.json', [])
anchors = {k: v for k, v in (load('anchors.json', {}) or {}).items() if not k.startswith('_')}
generic = {k: v for k, v in (load('generic_targets.json', {}) or {}).items() if not k.startswith('_')}
rew = load('reward_items_report.json', {'built': {}, 'missing': {}})
need = load('reward_items_needed.json', {'items': {}, 'unrecorded': []})
val = load('validation.json', {})
dlg = load('dialogue.json', {})
resolved = load('resolved.json', [])

L = []
w = L.append
rows = prev['rows']
srcs = {r['src'] for r in rows}
w('# Goal 8 quest ledger (classic quests: what is not straight from a period page)\n')
w(f"Generated by `quests/ledger_goal8.py`. Quest rows {len(rows)} ({len(srcs)} quests; per-class rows where rewards or trainers differ), "
  f"validator pass {len(rows) - len(val)} / fail {len(val)}.\n")

w('## Dialogue\n')
offer_rec = sum(1 for s in srcs if (dlg.get(s) or {}).get('offer'))
w(f"- Offer text recorded on the period page: {offer_rec} quests; the other {len(srcs) - offer_rec} use the walkthrough's description of the offer "
  "(no period wording recorded anywhere checked).")
w(f"- Accept keyword: the recorded chain's word where the page has one, else a word of the offer (owner rule: an existing quest word even if not the period one).")
ph = sum(1 for s in srcs if (dlg.get(s) or {}).get('checked') and not (dlg.get(s) or {}).get('accept_line'))
w(f"- Step 1 NPC line is the step's instruction (placeholder, owner rule: only when no recorded line): {ph} quests.")
choose = sum(1 for q in conf['Quests'].values() for st in q['Steps'][1:] if st and (st.get('Custom') or {}).get('Kind') == 'choose')
w(f"- Reward choice line \"Choose your reward: [..]\" (placeholder wording; the choice itself is from the page): {choose} steps.\n")

w('## Spawns this build adds\n')
src_count = collections.Counter((e.get('place') or {}).get('source', 'none') for e in plan)
w('Places: ' + ', '.join(f"{k} {v}" for k, v in src_count.most_common()) + '.\n')
w('### Borrowed looks (no period source records a creature\'s model)\n')
for m in world['mobs']:
    if m.get('_donor'):
        w(f"- {m['Name']} (level {m['Level']}, {'peaceful' if m['Realm'] else 'monster'}): looks like {m['_donor']}")
w('\n### Places from walkthrough text or hand research\n')
for name, a in sorted(anchors.items()):
    if a.get('why'): w(f"- {name}: {a['why']}")
for e in plan:
    if (e.get('place') or {}).get('source') == 'Uthgard map':
        w(f"- {e['name']}: Uthgard 2.0 bestiary map dot (later freeshard; no period location found)")
w('\n### Still without a place (not spawned; their quests are not loaded)\n')
for e in plan:
    if not (e.get('place') or {}).get('on_mesh'):
        w(f"- {e['realm']} {e['name']} ({e.get('zone')}) - {', '.join(e['quests'][:3])}")
w('\n## Hand-resolved generic targets ("<guard>", "<faerie court>")\n')
for k, v in generic.items():
    w(f"- {k}: {v.get('npc') or v.get('trainer_of') or v.get('spawn', {}).get('name')} - {v['why']}")
w('\n## Reward items\n')
w(f"- Built from period item pages: {len(rew['built'])}; models borrowed for all of them (same slot/type/realm, nearest level).")
procs = [(k, n) for k, v in rew['built'].items() for n in v['notes'] if '->' in n or 'no server' in n]
for k, n in procs: w(f"- {rew['built'][k]['name']}: {n}")
w(f"- No item page found yet (reward not given until found): {len(rew['missing'])}")
for k, v in sorted(rew['missing'].items(), key=lambda kv: kv[1]['name'])[:400]:
    w(f"  - {v['name']} ({v['realm']}) - {', '.join(v['quests'][:2])}")
for q, m in need.get('unrecorded', []):
    w(f"- {q}: the page leaves a reward unrecorded ({m})")
w('\n## Other substitutions\n')
w("- Buy steps with no merchant on this server selling the item (Tainted Magic's ales): the quest hands the item over.")
w("- Kill-task drop chances not on the page: 15-50% as listed in the specs (from the page wording 'sometimes' / 'for every').")
w("- \"You are awarded experience!\" with no number: a quarter of the quest's usual XP share.")
w("- Reawakening is part of Cad Goddeau A (prerequisite of Cad Goddeau B).")
open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('wrote', OUT, len(L), 'lines')
