"""Writes the bot camp list section for the goal 9 spawns and the Howth/Connla restoration rows into
GameServer/bots/autonomous/data/classic165_period_restored_spawn_ids.txt (an embedded resource: the camp planner offers
live spawns with these ids as grind camps). Re-run after goal9_plan.py; rebuild the server to ship it."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
P = os.path.join(HERE, '..', '..', '..', 'server', 'GameServer', 'bots', 'autonomous', 'data', 'classic165_period_restored_spawn_ids.txt')
MARK = '# goal 9 bestiary spawns and Howth/Connla restoration (generated by research/period-data/bestiary/goal9_camp_ids.py)'
raw = open(P, encoding='utf-8', newline='').read()
nl = '\r\n' if '\r\n' in raw else '\n'
keep, _, rest = raw.partition(nl + MARK)
keep = keep.rstrip(nl)
# sections written after this one (classic quest camps) are kept
later = rest.split(nl)
later = nl.join(later[next((k for k, l in enumerate(later) if k > 0 and l.startswith('#')), len(later)):])
plan = json.load(open(os.path.join(HERE, 'goal9_plan.json'), encoding='utf-8'))['rows']
gone = set(json.load(open(os.path.join(HERE, 'hc_in_town.json'))))
hc = [r['Mob_ID'] for r in json.load(open(os.path.join(HERE, 'hc_plan.json')))['rows'] if r['Mob_ID'] not in gone]
ids = list(dict.fromkeys([r['Mob_ID'] for r in plan] + hc))
open(P, 'w', encoding='utf-8', newline='').write(keep + nl + MARK + nl + nl.join(ids) + nl + (later.rstrip(nl) + nl if later.strip() else ''))
print('ids', len(ids), 'goal 9', len(plan), 'howth/connla', len(hc))
